// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMN0WU2q2fa_EQIi6DsU8h1PD4xTkVK7Q',
    appId: '1:212105992725:web:053b0bf188aa067fc34c1c',
    messagingSenderId: '212105992725',
    projectId: 'systemprojectgroup1',
    authDomain: 'systemprojectgroup1.firebaseapp.com',
    storageBucket: 'systemprojectgroup1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9pUWpZnauRrGLu3Me3tBuNsoJpgEqMA',
    appId: '1:212105992725:android:da25fb4a87872f7fc34c1c',
    messagingSenderId: '212105992725',
    projectId: 'systemprojectgroup1',
    storageBucket: 'systemprojectgroup1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-R-9sIhW9_UfZj1q2HrzmI0TiwOSQH34',
    appId: '1:212105992725:ios:a975618771c6e2ffc34c1c',
    messagingSenderId: '212105992725',
    projectId: 'systemprojectgroup1',
    storageBucket: 'systemprojectgroup1.appspot.com',
    iosClientId: '212105992725-qc5r2fae9jqlg1up6s31rdd6q6nginvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
